% Main GA script for Flying Base Station Optimization

clearvars;

% Setup antennas and MBS parameters
fbsAntenna = setup_antenna();
mbsAntenna = setup_antenna();
antennaObjectMbs = [mbsAntenna];
mbs_x = [300];       
mbs_y = [350];     
mbs_height = [25];        
mbs_power = [20]; 
mbs_params = [mbs_x; mbs_y; mbs_height; mbs_power];
containsMbs = 1;
numBS = 2;

% Optimization parameters
params = struct(...
    'populationSize', 100, ...
    'numGenerations', 10, ...
    'crossoverProb', 0.3, ...
    'mutationProb', 0.7, ...
    'numBS', numBS, ...
    'bounds', repmat([0 1500; 0 1500; 20 150; 7 10.5; 0 1], numBS, 1), ...
    'mutationScale', 0.17, ...
    'spaceLimit', 1500, ... 
    'verbose', 1 ...
);

[bestInd, bestFit, history] = optimizeBaseStation( ...
    fbsAntenna, containsMbs, antennaObjectMbs, mbs_params, params);